CREATE TABLE IF NOT EXISTS SW_USR (
	OBJECT_ID BIGSERIAL PRIMARY KEY,
	USR_NAME VARCHAR (50) UNIQUE NOT NULL,
	USR_PASSWORD VARCHAR (50) NOT NULL,
	USR_EMAIL VARCHAR (255) UNIQUE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);
SELECT OBJECT_ID,
	USR_NAME,
	USR_PASSWORD,
	USR_EMAIL,
	CREATED_AT
FROM SW_USR
WHERE USR_EMAIL = $1
	AND USR_PASSWORD = $2