CREATE TABLE IF NOT EXISTS SW_USR (
	OBJECT_ID BIGSERIAL PRIMARY KEY,
	USR_USERNAME VARCHAR (50) UNIQUE NOT NULL,
	USR_PASSWORD VARCHAR (50) NOT NULL,
	USR_EMAIL VARCHAR (255) UNIQUE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);
